### ISSUE TITLE
No quick navigation in SecretsManager

### ISSUE THREAD

**Issue by gdlx** [akinjide/refined-aws#2]
Hi !

The quick navigation bar with pinned services isn't shown in Secrets Manager UI.

**Comment by akinjide** [comment]
[refined-aws@2.3.2](https://github.com/akinjide/refined-aws/tree/2.3.2) fix: pkg vulnerability and quick nav in secretsManager

**Comment by akinjide** [comment]
update extension

**Comment by gdlx** [comment]
Works fine, thanks !

**Comment by gdlx** [comment]
There's also an issue in the following Service Catalog pages:

- Products list
- Provisioned products list
- TagOption library
-Service actions

![image](https://user-images.githubusercontent.com/1533042/65023319-d82e0e80-d932-11e9-805f-9da1b1556ebb.png)

But it works fine for Service Catalog products and portfolio lists...still much heterogeneity in AWS console...

**Comment by akinjide** [comment]
[refined-aws@2.3.3 ](https://github.com/akinjide/refined-aws/tree/2.3.3) fix: shrink navigation in service catalog

**Comment by akinjide** [comment]
update extension @gdlx
