### ISSUE TITLE
FireFox Deploy

### ISSUE THREAD

**Issue by akinjide** [akinjide/refined-aws#7]
<img width="1440" alt="Screenshot 2020-07-17 at 01 09 15" src="https://user-images.githubusercontent.com/11836769/87734350-48632600-c7ca-11ea-87ed-74c92dda3024.png">

@dennisroche Got that error on firefox store publish and it might be preventing extension from going public

**Comment by dennisroche** [comment]
The error is that it isn't `Compatitible with Firefox Quantum`?

It might just a manifest change. I can take a look today.

**Comment by akinjide** [comment]
> The error is that it isn't `Compatitible with Firefox Quantum`?
> 
> It might just a manifest change. I can take a look today.

Okay, what version is recommended and what manifest change is required?

**Comment by akinjide** [comment]
Available at [https://addons.mozilla.org/en-GB/firefox/addon/refined-aws-console/](https://addons.mozilla.org/en-GB/firefox/addon/refined-aws-console/)

**Comment by akinjide** [comment]
Thanks @dennisroche, closing issue.

**Comment by dennisroche** [comment]
thanks for resolving this; apologies for never getting to back it.
