### ISSUE TITLE
Align extension with AWS new console UI

### ISSUE THREAD

**Issue by akinjide** [akinjide/refined-aws#9]
AWS new console UI will potentially break extension functionality. Plan to upgrade chrome extension to implement new console UI breaking changes.

<img width="1057" alt="Screenshot 2020-09-23 at 11 08 46" src="https://user-images.githubusercontent.com/11836769/94052074-4d75c000-fd8d-11ea-9cd2-77f4a0d2aeaf.png">

**Comment by wobondar** [comment]
Yes, please. Looking forward to your enhancement. Thank you!

**Comment by akinjide** [comment]
Release [v2.6.0](https://github.com/akinjide/refined-aws/releases/tag/2.6.0) aligns extension with new UI. Please look out for upgrade at [https://chrome.google.com/webstore/detail/refined-aws-console/ockddcaogdonfmcfhdblbflchnjgiilc](https://chrome.google.com/webstore/detail/refined-aws-console/ockddcaogdonfmcfhdblbflchnjgiilc)
